kind: pipeline
name: default

type: docker
steps:
  - name: lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run --enable-all
  - name: migration
    image: golang
    commands:
      - go run main.go migrate
    environment:
      MONITOR_DB_HOST: "database"
      MONITOR_DB_PORT: 5432
      MONITOR_REDIS_HOST: "redis"
      MONITOR_REDIS_PORT: 6379
  - name: test
    image: golang
    commands:
      - go test -v ./...
    environment:
      MONITOR_DB_HOST: "database"
      MONITOR_DB_PORT: 5432
      MONITOR_REDIS_HOST: "redis"
      MONITOR_REDIS_PORT: 6379

services:
  - name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitor
  - name: redis
    image: redis:latest