version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monitor
    ports:
      - 5431:5432
  redis:
    image: redis:latest
    ports:
    - 6378:6379
  nats:
    image: nats:latest
    ports:
      - 4221:4222